global:
  idpAppConfig:
    imageRepositories:
      docker.io: "docker.io"
      quay.io: "quay.io"

    clusters:
      test:
        #aws_region: eu-central-1
        domains:
          example.com: example.com
        nodePools:
          test1:
            nodeSelector:
              environment: test
            tolerations:
              - key: environment
                operator: Equal
                value: test
                effect: NoSchedule

    defaults:
      imageRepository: docker.io
      imagePullPolicy: IfNotPresent
      ingress:
        enabled: false
        className: traefik-private
        certManagerClusterIssuer: letsencrypt
        #  fcgi:
        #    documentRoot: /html
        path: /
        #rewriteTarget: /api
        annotations: { }
        basicAuth:
          enabled: false
          secretName:
        oauth2ProxyAuth:
          enabled: false
          url: null
          # overwrites url for signin url when specified
          urlExternal: null
          # https://oauth2-proxy.github.io/oauth2-proxy/features/endpoints#auth
          allowedGroups: null # []
          responseHeaders:
            - Auth-Proxy-Email
            - Auth-Proxy-Groups
          path: /oauth2
          service:
            name: null
            port: 80
        accessLog:
          enabled: true
      configs:
        annotations: {}
          # we want argocd to sync configs first, then the rest of deployment
          #argocd.argoproj.io/sync-wave: "-10"
        externalSecret:
          # reload of external-secret using annotation stopped working with refreshInterval=0
          # we set it to very long period now, so it does not reload, but annotations work
          # https://github.com/external-secrets/external-secrets/pull/4086
          # https://github.com/external-secrets/external-secrets/issues/3979
          refreshInterval: "99999h"