{{- if not .Values.debug -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mz-app.serviceAccountName" . }}
  labels:
    {{- include "mz-app.labels" . | nindent 4 }}
  annotations:
    "eks.amazonaws.com/role-arn": {{ required "serviceAccount.awsRoleArn required" .Values.serviceAccount.awsRoleArn | quote }}
{{- end }}
{{- end}}