{{- if not $.Values.debug -}}
{{- if $.Values.cronjob.enabled }}
{{- $this := $.Values.cronjob }}
{{- $deployments := (dict "" dict) }}
{{- range $deploymentKey, $deployment := $deployments }}
{{- $deploymentName := include "idp-app.deploymentName" (list $ $deploymentKey) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "idp-app.labels" $ | nindent 4 }}
  {{- with $this.annotations }}
  annotations:
    {{- toYaml $this.annotations | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ required "cronjob.schedule required" $this.schedule | quote }}
  {{- if hasKey $this "suspend" }}
  suspend: {{ $this.suspend }}
  {{- end }}
  concurrencyPolicy: {{ $this.concurrencyPolicy | required "cronjob.concurrencyPolicy required" | quote }}
  {{- if $this.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ $this.startingDeadlineSeconds }}
  {{- end }}
  successfulJobsHistoryLimit: {{ $this.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $this.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "idp-app.labels" $ | nindent 8 }}
    spec:
      template:
        {{- include "idp-app.podTemplate" (list $ $deploymentKey $deployment ) | nindent 8 }}
---
{{- end }}
{{- end }}
{{- end }}