{{- if not $.Values.debug -}}
{{- if $.Values.deployment.enabled }}
{{- if not $.Values.deployment.managedByUmbrella }}
{{- include "idp-app.deployments" (list $ $.Values) }}
{{- end }}
{{- end }}
{{- end }}
