{{- if not .Values.debug -}}
{{- if and $.Values.deployment.enabled .Values.autoscaling.enabled }}
{{- $deployments := default (dict "" dict) $.Values.deployment.multi }}
{{- range $deploymentKey, $deployment := $deployments }}
{{- $deploymentName := include "idp-app.deploymentName" (list $ $deploymentKey) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "idp-app.labelsMulti" (list $ $deploymentKey) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ $.Values.deployment.kind }}
    name: {{ include "idp-app.fullname" $ }}{{- if $deploymentKey }}-{{ $deploymentKey }}{{- end }}
  minReplicas: {{ required "autoscaling.minReplicas required" $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ required "autoscaling.maxReplicas required" $.Values.autoscaling.maxReplicas }}

  behavior:
    {{- $presets := (((($.Values.global).idpAppConfig).defaults).autoscaling).presets | default dict }}
    {{- with include "idp-app.hpaScaleDir" (list ($.Values.autoscaling.scaleDown | default dict) ($presets.scaleDown | default dict) "scaleDown") }}
    scaleDown:
      {{- . | nindent 6 }}
    {{- end }}
    {{- with include "idp-app.hpaScaleDir" (list ($.Values.autoscaling.scaleUp | default dict) ($presets.scaleUp | default dict) "scaleUp") }}
    scaleUp:
      {{- . | nindent 6 }}
    {{- end }}

  metrics:
    {{- if $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}