{{- if not $.Values.debug -}}
{{- if $.Values.job.enabled }}
{{- $this := $.Values.job }}
{{- $deployments := (dict "" dict) }}
{{- range $deploymentKey, $deployment := $deployments }}
{{- $deploymentName := include "idp-app.deploymentName" (list $ $deploymentKey) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "idp-app.labels" $ | nindent 4 }}
  {{- with $this.annotations }}
  annotations:
    {{- toYaml $this.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if hasKey $this "activeDeadlineSeconds" }}
  activeDeadlineSeconds: {{ $this.activeDeadlineSeconds }}
  {{- end }}
  {{- if hasKey $this "backoffLimit" }}
  backoffLimit: {{ $this.backoffLimit }}
  {{- end }}
  {{- if hasKey $this "completionMode" }}
  completionMode: {{ $this.completionMode }}
  {{- end }}
  {{- if hasKey $this "completions" }}
  completions: {{ $this.completions }}
  {{- end }}
  {{- if hasKey $this "parallelism" }}
  parallelism: {{ $this.parallelism }}
  {{- end }}
  {{- if hasKey $this "suspend" }}
  suspend: {{ $this.suspend }}
  {{- end }}
  {{- if hasKey $this "podReplacementPolicy" }}
  podReplacementPolicy: {{ $this.podReplacementPolicy }}
  {{- end }}
  {{- if hasKey $this "ttlSecondsAfterFinished" }}
  ttlSecondsAfterFinished: {{ $this.ttlSecondsAfterFinished }}
  {{- end }}
  {{- if hasKey $this "podFailurePolicy" }}
  podFailurePolicy:
    {{- toYaml $this.podFailurePolicy | nindent 4 }}
  {{- end }}
  {{- if hasKey $this "successPolicy" }}
  successPolicy:
    {{- toYaml $this.successPolicy | nindent 4 }}
  {{- end }}
  {{- if hasKey $this "backoffLimitPerIndex" }}
  backoffLimitPerIndex: {{ $this.backoffLimitPerIndex }}
  {{- end }}
  template:
    {{- include "idp-app.podTemplate" (list $ $deploymentKey $deployment ) | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}