{{- if not .Values.debug -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "idp-app.serviceAccountName" . }}
  labels:
    {{- include "idp-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.awsRoleArn }}
    "eks.amazonaws.com/role-arn": {{ . | quote }}
    {{- end }}
{{- end }}
{{- end}}