{{- if not $.Values.debug -}}
{{- if $.Values.statefulset.enabled }}
{{- if not $.Values.statefulset.managedByUmbrella }}
{{- include "idp-app.workload" (list $ $.Values) }}
{{- end }}
{{- end }}
{{- end }}
